// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package services

import (
	"github.com/google/wire"
	"github.com/infinity-oj/server-v2/internal/app/judgements/repositories"
	repositories4 "github.com/infinity-oj/server-v2/internal/app/problems/repositories"
	repositories2 "github.com/infinity-oj/server-v2/internal/app/processes/repositories"
	repositories3 "github.com/infinity-oj/server-v2/internal/app/submissions/repositories"
	"github.com/infinity-oj/server-v2/internal/pkg/configs"
	"github.com/infinity-oj/server-v2/internal/pkg/database"
	"github.com/infinity-oj/server-v2/internal/pkg/log"
)

// Injectors from wire.go:

func CreateJudgementsService(cf string, sto repositories.Repository, sto2 repositories2.Repository, sto3 repositories3.Repository, sto4 repositories4.Repository) (JudgementsService, error) {
	viper, err := configs.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	judgementsService := NewJudgementsService(logger, sto, sto4, sto2, sto3)
	return judgementsService, nil
}

// wire.go:

var testProviderSet = wire.NewSet(log.ProviderSet, configs.ProviderSet, database.ProviderSet, ProviderSet)
