app:
  name: server
http:
  mode: debug
  host: 127.0.0.1
  port: 8888
db:
  url: host=db user=postgres password=postgres dbname=postgres sslmode=disable
  debug: false
log:
  filename: logs/server.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
jaeger:
  serviceName: server
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
volumes:
  type: local
  base: test_files
